### ISSUE TITLE
Klasa Kviz

### ISSUE THREAD

**Issue by lenastankovic2007** [lenastankovic2007/kviz#2]
Unutar klase Kviz, gde su atributi lista svih dostupnih pitanja i ukupan broj poena, definisati metode za dodavanje, brisanje i izmenu pitanja.
DodajPitanje(Pitanje pitanje) (void): Dodaje pitanje u kolekciju.
IzmeniPitanje(int indeks, Pitanje novoPitanje) (void): Menja pitanje na datom indeksu.
ObrisiPitanje(int indeks) (void): Briše pitanje iz liste.

**Comment by n-ratinac** [comment]
Mislim da je bolje da postoji klasa koja je iskljucivo zaduzena za rad sa skladistem npr. StorageManager. Linkovacu novi issue. Sto se tice klase kviz, ne radimo do daljnjeg.
