### ISSUE TITLE
Klasa QuestionBank

### ISSUE THREAD

**Issue by n-ratinac** [lenastankovic2007/kviz#6]
Neka ova klasa implementira funkcionalnosti za rad sa kolekcijom pitanja.

## Metode
AddQuestion(Question) koje dato pitanje dodaje na kraj liste pitanja.
DeleteQuestion(int ID) koje brise pitanje sa datim ID-em.
ListQuestions() koja vraca string oblika:
```
ID1,TekstPitanja1
ID2,TekstPitanja2
...
IDN,TekstPitanjaN
```
RandomQuestions(int n, int m) vraca listu od n nasumicnih pitanja tezine m

**Comment by n-ratinac** [comment]
Za ovo je potrebno samo da imamo atribute iz Question klase da bismo radili. 

Ovde linkujem issue #1 kako bismo bili usaglaseni

**Comment by lenastankovic2007** [comment]
Dobro veče,
Nastavniče, završiću večeras ovo, samo možda pošaljem malo kasnije uveče,
pošto sam na rodjendanu. Krenuću i da pravim klasu Kviz.

**Comment by n-ratinac** [comment]
Nema problema

**Comment by lenastankovic2007** [comment]
kako znam koje tezine mi je pitanje, posto trenutno ne postoji atribut kojim se to opisuje? nisam bila sigurna za to pa sam poslednju metodu ostavila praznom

**Comment by lenastankovic2007** [comment]
tezine ce biti 1, 2 i 3 gde je 1 najlaksa, 2 srednja a 3 najmanja
tezina se gleda u odnosu na broj poena (ako je 10 poena to j najlakse, 30 najteze), pogledati issue pitanja

**Comment by lenastankovic2007** [comment]
je l mogu pull request za ovo

**Comment by n-ratinac** [comment]
Naravno, odradi merge na main granu posle

**Comment by lenastankovic2007** [comment]
Je l za to moram da cekam da tamara zavrsi, ili mogu sad, pa ona samo da
pull-uje opet?

**Comment by n-ratinac** [comment]
Ne radite na istom fajlu, tako da ne mora ona da pulluje
